name: Release Extensions

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1.5.0
      - run: chrome --version
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Install Chrome dependencies
        run: |
          cd chrome
          npm install

      - name: Install Firefox dependencies
        run: |
          cd firefox
          npm install

      - name: Build Chrome Extension
        run: |
          cd chrome
          npm run build

      - name: Build Firefox Extension
        run: |
          cd firefox
          web-ext build

      - name: Check for version change
        id: check_version
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const version = fs.readFileSync('version.txt', 'utf8').trim();
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            if (releases.data.length ===  0) {
              return {
                result: true,
                version: version
              };
            }

            const latestRelease = releases.data[0];
            if (latestRelease.tag_name === version) {
              return false;
            }

            return {
              result: true,
              version: version
            };
      
      - name: debug
        run: |
          ls ./chrome/dist/
          echo "---"
          ls ./chrome/dist/src

      - name: Create Release
        id: create_release
        if: fromJson(steps.check_version.outputs.result).result == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ fromJson(steps.check_version.outputs.result).version }}
          release_name: Release v${{ fromJson(steps.check_version.outputs.result).version }}
          draft: false
          prerelease: false

      - name: Upload Firefox Extension
        if: fromJson(steps.check_version.outputs.result).result == true
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firefox/web-ext-artifacts/extension.xpi
          asset_name: extension.xpi
          asset_content_type: application/octet-stream
      
      - name: Upload Chrome Extension
        if: fromJson(steps.check_version.outputs.result).result == true
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chrome/dist/extension.crx
          asset_name: extension.crx
          asset_content_type: application/octet-stream
